export { default as Logo } from "./Logo";
export { default as BigSidebar } from "./BigSidebar";
export { default as SmallSidebar } from "./SmallSidebar";
export { default as NavLinks } from "./NavLinks";
export { default as Navbar } from "./Navbar";
export { default as FormRow } from "./FormRow";
export { default as PeopleContainer } from "./PeopleContainer";
export { default as PersonInfo } from "./PersonInfo";
export { default as Person } from "./Person";
